name: Node CI (PR)
on:
  pull_request:
    paths-ignore:
      - "**"
      - "!**.js"
      - "!**.json"
      - "!**.css"
      - "!**.html"
      - "!.github/workflows/**"
      - "!.snyk"

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome

jobs:
  lint:
    name: Check linting issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "I ran"
